version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tx_repo
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
